# [ get_pdf_report_html 関数を以下に差し替え ]

def get_pdf_report_html(summ_df, sel_plan_name):
    # 背景を赤からGasio Blueへ変更、文言を「生成」に修正
    # データフレームをより美しくフォーマットしたHTML
    formatted_table = summ_df.style.format({
        "売上総額": "¥{:,.0f}",
        "差額": "¥{:,.0f}",
        "増減率": "{:+.2f}%"
    }).to_html(index=False)

    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <style>
            body {{ font-family: "Helvetica Neue", Arial, sans-serif; padding: 50px; color: #2c3e50; line-height: 1.6; }}
            .report-header {{ border-bottom: 2px solid #3498db; padding-bottom: 20px; margin-bottom: 30px; display: flex; justify-content: space-between; align-items: flex-end; }}
            .report-title {{ font-size: 28px; font-weight: bold; color: #2c3e50; margin: 0; }}
            .date {{ color: #7f8c8d; font-size: 14px; }}
            .section-title {{ font-size: 18px; font-weight: bold; margin-top: 40px; margin-bottom: 15px; border-left: 5px solid #3498db; padding-left: 10px; }}
            table {{ width: 100%; border-collapse: collapse; margin-top: 10px; font-size: 14px; }}
            th {{ background-color: #f8f9fa; color: #34495e; padding: 12px; border: 1px solid #dee2e6; text-align: center; }}
            td {{ padding: 12px; border: 1px solid #dee2e6; text-align: right; }}
            tr:nth-child(even) {{ background-color: #fcfcfc; }}
            .best-plan {{ color: #e74c3c; font-weight: bold; }}
            .footer {{ margin-top: 50px; font-size: 12px; color: #95a5a6; text-align: center; border-top: 1px solid #eee; padding-top: 20px; }}
            @media print {{ .no-print {{ display: none; }} body {{ padding: 20px; }} }}
        </style>
    </head>
    <body>
        <div class="report-header">
            <h1 class="report-title">ガス料金改定シミュレーション報告書</h1>
            <span class="date">作成日: {datetime.datetime.now().strftime('%Y年%m月%d日')}</span>
        </div>
        
        <div class="section-title">1. 収支シミュレーション結果一覧</div>
        <p>現行料金体系と設計した新プランとの売上比較（年換算）は以下の通りです。</p>
        {formatted_table}
        
        <div class="section-title">2. 分析概要</div>
        <p>本報告書は「{sel_plan_name}」を主対象としたシミュレーション結果に基づいています。</p>
        
        <div class="footer">
            Gasio Cloud Edition - Generated by Simulation Engine
        </div>
        
        <div class="no-print" style="margin-top: 30px; text-align: center;">
            <button onclick="window.print()" style="padding: 10px 20px; background-color: #3498db; color: white; border: none; border-radius: 5px; cursor: pointer; font-weight: bold;">
                🖨️ PDFとして保存 / 印刷
            </button>
        </div>
    </body>
    </html>
    """
    
    # 確実にデータを渡すためにエンコード処理
    try:
        b64 = base64.b64encode(html_content.encode('utf-8')).decode('utf-8')
        button_style = "width:100%; height:40px; background-color:#3498db; color:white; border:none; border-radius:4px; cursor:pointer; font-weight:bold;"
        return f'<a href="data:text/html;charset=utf-8;base64,{b64}" target="_blank" style="text-decoration:none;"><button style="{button_style}">📄 報告用レポートを生成</button></a>'
    except Exception as e:
        return f"レポート生成エラー: {str(e)}"

# [ Tab 2 の呼び出し部分も以下のように調整 ]
# st.markdown(get_pdf_report_html(pd.DataFrame(summ_list), sel_p), unsafe_allow_html=True)
